l_russian:
  newsfeed_subject_self_label: "Мои личные события"
  newsfeed_subject_spouse_label: "События, в которых участвует [spouse|E]"
  newsfeed_subject_close_dynastic_family_label: "События тех, у кого [close_family|E] с моей [dynasty|E]"
  newsfeed_subject_extended_dynastic_family_label: "События тех, у кого [extended_family|E] с моей [dynasty|E]"
  newsfeed_subject_liege_label: "События, в которых участвует мой [liege|E]"
  newsfeed_subject_direct_vassal_label: "События, в которых мои прямые [vassals|E]"
  newsfeed_subject_pinned_character_label: "События закрепленных мной персонажей"

  newsfeed_type_marriage_label: "Браки"
  newsfeed_type_pregnancy_label: "Зачатия"
  newsfeed_type_birth_label: "Рождения"
  newsfeed_type_death_label: "Смерти"
  newsfeed_type_offensive_war_label: "Наступательных войн"
  newsfeed_type_defensive_war_label: "Оборонительных войн"
  newsfeed_type_titles_label: "Титулы"