l_korean:
  newsfeed_subject_self_label: "$CHARACTER_NAME_ME$"
  newsfeed_subject_spouse_label: "[spouse|E]"
  newsfeed_subject_close_dynastic_family_label: "[dynasty|E]에 속해 있는 [close_family|E]"
  newsfeed_subject_extended_dynastic_family_label: "[dynasty|E]에 속해 있는 [extended_family|E]"
  newsfeed_subject_dynasty_label: "[dynasty|E]의 모든 인물"
  newsfeed_subject_liege_label: "[liege|E]"
  newsfeed_subject_direct_vassal_label: "[vassals|E]"
  newsfeed_subject_courtier_label: "[courtiers|E]"
  newsfeed_subject_pinned_character_label: "고정된 인물"

  newsfeed_type_marriage_label: "[marriage|E]"
  newsfeed_type_pregnancy_label: "임신"
  newsfeed_type_birth_label: "탄생"
  newsfeed_type_death_label: "사망"
  newsfeed_type_offensive_war_label: "[war|E] (공격)"
  newsfeed_type_defensive_war_label: "[war|E] (방어)"
  newsfeed_type_titles_label: "[title|E]"
