l_simp_chinese:
 newsfeed_subject_self_label: "我"
 newsfeed_subject_self_icon: "@newsfeed_icon_self!"
 newsfeed_subject_spouse_label: "我的[spouse|E]"
 newsfeed_subject_spouse_icon: "@newsfeed_icon_spouse!"
 newsfeed_subject_close_dynastic_family_label: "我的[dynasty|E]的[close_family|E]"
 newsfeed_subject_close_dynastic_family_icon: "@newsfeed_icon_close_dynastic_family!"
 newsfeed_subject_extended_dynastic_family_label: "我的[dynasty|E]的[extended_family|E]"
 newsfeed_subject_extended_dynastic_family_icon: "@newsfeed_icon_extended_dynastic_family!"
 newsfeed_subject_liege_label: "我的[liege|E]"
 newsfeed_subject_liege_icon: "@newsfeed_icon_liege!"
 newsfeed_subject_direct_vassal_label: "我的直属[vassals|E]"
 newsfeed_subject_direct_vassal_icon: "@newsfeed_icon_direct_vassal!"
 newsfeed_subject_pinned_character_label: "我的固定角色"
 newsfeed_subject_pinned_character_icon: "@newsfeed_icon_pinned_character!"
 newsfeed_type_marriage_label: "婚姻"
 newsfeed_type_pregnancy_label: "怀孕"
 newsfeed_type_birth_label: "出生"
 newsfeed_type_death_label: "死亡"
 newsfeed_type_war_label: "战争"
 newsfeed_type_titles_label: "头衔"